name: PR Checks
on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize]

permissions:
  contents: read
  actions: write

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Gradle
        run: ./gradlew build

  gradle_publish:
    runs-on: ubuntu-latest
    container:
      image: amazoncorretto:17.0.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gradle Publish
        run: ./gradlew --build-cache publishToSonatype closeAndReleaseSonatypeStagingRepository
